<div class="main-bottom" align="center">
	<?php
		if(isset($_GET['ac']))
		{
			if($_GET['ac']=='banner')
			{
				include("modules/banner/them.php");
				include("modules/banner/lietke.php");
			}
			if($_GET['ac']=='loaitin')
			{
				include("modules/loaitin/them.php");
				include("modules/loaitin/lietke.php");
			}
			if($_GET['ac']=='theloai')
			{
				include("modules/theloai/them.php");
				include("modules/theloai/lietke.php");
			}
			if($_GET['ac']=='tintuc')
			{
				include("modules/tintuc/them.php");
				include("modules/tintuc/lietke.php");
			}
			if($_GET['ac']=='album')
			{
				include("modules/album/them.php");
				include("modules/album/lietke.php");
			}
			if($_GET['ac']=='image')
			{
				include("modules/image/them.php");
				include("modules/image/lietke.php");
			}
		}
		if(isset($_GET['sua']))
		{
			if($_GET['sua']=='banner')
			{
				include("modules/banner/sua.php");
				include("modules/banner/lietke.php");
			}
			if($_GET['sua']=='loaitin')
			{
				include("modules/loaitin/sua.php");
				include("modules/loaitin/lietke.php");
			}
			if($_GET['sua']=='theloai')
			{
				include("modules/theloai/sua.php");
				include("modules/theloai/lietke.php");
			}
			if($_GET['sua']=='tintuc')
			{
				include("modules/tintuc/sua.php");
				include("modules/tintuc/lietke.php");
			}
			if($_GET['sua']=='album')
			{
				include("modules/album/sua.php");
				include("modules/album/lietke.php");
			}
			if($_GET['sua']=='image')
			{
				include("modules/image/sua.php");
				include("modules/image/lietke.php");
			}
		}
	?>
</div>
<div class="xoa">
</div>